from docx import Document
from pydantic import BaseModel

from app.core.config import ROOT, settings
from app.core.hashing import sha256_bytes
from app.core.models import CreateReleaseSheetRequest
from app.core.storage import blob_store
from app.core.template import validate_template_ref

from pathlib import Path
from pydantic import BaseModel

from app.core.config import ROOT, settings
from app.core.hashing import sha256_bytes
from app.core.models import CreateReleaseSheetRequest
from app.core.storage import blob_store
from app.core.template import validate_template_ref
from app.core.storage import blob_store
from app.core.config import settings, ROOT
from app.core.hashing import sha256_bytes

class RenderResult(BaseModel):
    ok: bool
    artifact_id: str | None = None
    filename: str | None = None
    blob_uri: str | None = None
    blob_name: str | None = None
    sha256: str | None = None
    error: str | None = None

def _add_kv(table, key, value):
    row = table.add_row().cells
    row[0].text = str(key)
    row[1].text = '' if value is None else str(value)

def render_release_sheet_docx(request: CreateReleaseSheetRequest) -> RenderResult:
    try:
        ts = validate_template_ref(request.template_ref)
        if not ts.ok or not ts.path:
            return RenderResult(ok=False, error=ts.error or 'template invalid')
        doc = Document(ts.path)
        rel = request.release
        filename = f"BRK_{rel.project.replace(' ', '_')}_System_Release_Sheet_{rel.delivery}_{rel.cat_level}.docx"
        artifact_id = f"srs-artifact-{rel.delivery}-{rel.cat_level}"
        doc.add_heading('System Release Sheet', level=1)
        doc.add_paragraph('Controlled documentation artifact. This document does not approve the release.')
        doc.add_heading('Release Information', level=2)
        t = doc.add_table(rows=1, cols=2); t.rows[0].cells[0].text='Field'; t.rows[0].cells[1].text='Value'
        for k,v in rel.model_dump().items(): _add_kv(t,k,v)
        doc.add_heading('Identification', level=2)
        t = doc.add_table(rows=1, cols=2); t.rows[0].cells[0].text='Field'; t.rows[0].cells[1].text='Value'
        for k,v in request.identification.model_dump().items(): _add_kv(t,k,v)
        doc.add_heading('Software Delivery Content', level=2)
        swt = doc.add_table(rows=1, cols=6)
        for i, h in enumerate(
            ["Name", "PTC Integrity ID", "ZF Version", "Customer Version", "Configuration Path", "To Whom"]
        ):
            swt.rows[0].cells[i].text = h
        for sw in request.software:
            vals = [
                sw.name,
                sw.ptc_integrity_id,
                sw.software_version_zf,
                sw.software_version_customer or "",
                sw.configuration_path or "",
                sw.to_whom or "",
            ]
            cells = swt.add_row().cells
            for i, val in enumerate(vals):
                cells[i].text = str(val)
        doc.add_heading("Reason for Release", level=2)
        for k, v in request.reason_for_release.model_dump().items():
            doc.add_paragraph(f'{k}: {v or ""}')
        doc.add_heading("Release Documentation References", level=2)
        for k, v in request.release_documentation.model_dump().items():
            doc.add_paragraph(f"{k}: {v}")
        doc.add_heading("Known Issues", level=2)
        doc.add_paragraph(f"Issues found: {request.known_issues.issues_found}")
        doc.add_paragraph(f'Driver information: {request.known_issues.driver_information or ""}')
        doc.add_heading('Approval / HITL Notice', level=2)
        doc.add_paragraph('Approval signatures require HITL completion. No signatures are generated by this harness.')
        tmp = ROOT / 'outputs' / filename
        tmp.parent.mkdir(exist_ok=True)
        doc.save(tmp)
        data = tmp.read_bytes()
        digest = sha256_bytes(data)
        stored = blob_store.upload_bytes(settings.artifacts_container, filename, data, overwrite=False, content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
        return RenderResult(ok=True, artifact_id=artifact_id, filename=filename, blob_uri=stored.blob_uri, blob_name=filename, sha256=digest)
    except Exception as exc:
        return RenderResult(ok=False, error=str(exc))
